from windmill.authoring import WindmillTestClient

def test_tests_acidentes_rodovias_regiao_windmill():
    client = WindmillTestClient(__name__)

    client.asserts.assertNode(link=u'Regi\xe3o')
    client.click(link=u'Regi\xe3o')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[1]', validator=u'Selecione um estado...')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[2]', validator=u'Acre')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[3]', validator=u'Alagoas')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[4]', validator=u'Amap\xe1')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[5]', validator=u'Amazonas')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[6]', validator=u'Bahia')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[7]', validator=u'Cear\xe1')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[8]', validator=u'Distrito Federal')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[9]', validator=u'Esp\xedrito Santo')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[10]', validator=u'Goi\xe1s')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[11]', validator=u'Maranh\xe3o')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[12]', validator=u'Mato Grosso')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[13]', validator=u'Mato Grosso do Sul')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[14]', validator=u'Minas Gerais')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[15]', validator=u'Para\xedba')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[16]', validator=u'Paran\xe1')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[17]', validator=u'Par\xe1')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[18]', validator=u'Pernambuco')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[19]', validator=u'Piaui')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[20]', validator=u'Rio de Janeiro')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[21]', validator=u'Rio Grande do Norte')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[22]', validator=u'Rio Grande do Sul')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[23]', validator=u'Rond\xf4nia')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[24]', validator=u'Roraima')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[25]', validator=u'Santa Catarina')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[26]', validator=u'S\xe3o Paulo')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[27]', validator=u'Sergipe')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[28]', validator=u'Tocantins')
    client.select(option=u'S\xe3o Paulo', id=u'customDropdown')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertNode(xpath=u'/html/body/form/div/div[1]/div/ul/li[60]')
    client.select(option=u'OSASCO', id=u'customDropdown')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertNode(link=u'OSASCO')
    client.asserts.assertNode(link=u'SP')
    client.asserts.assertText(xpath=u'/html/body/div[3]/div[1]/div/div/div/h4/span', validator=u'393275')
    client.click(link=u'Regi\xe3o')
    client.waits.forPageLoad(timeout=u'20000')
    client.select(option=u'Bahia', id=u'customDropdown')
    client.click(xpath=u'/html/body/form/div/div[1]/div/ul/li[6]')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.select(option=u'BARREIRAS', id=u'customDropdown')
    client.click(xpath=u'/html/body/form/div/div[1]/div/ul/li[16]')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertNode(link=u'BARREIRAS')
    client.asserts.assertNode(link=u'BA')
    client.asserts.assertText(xpath=u'/html/body/div[3]/div[1]/div/div/div[698]/h4/span', validator=u'1123366')
    client.click(link=u'Regi\xe3o')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', id=u'btn_submit')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[1]', validator=u'Selecione um munic\xedpio...')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[2]', validator=u'ACRELANDIA')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[3]', validator=u'ASSIS BRASIL')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[4]', validator=u'BRASILEIA')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[5]', validator=u'BUJARI')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[6]', validator=u'CAPIXABA')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[7]', validator=u'CRUZEIRO DO SUL')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[8]', validator=u'EPITACIOLANDIA')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[9]', validator=u'MANOEL URBANO')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[10]', validator=u'PLACIDO DE CASTRO')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[11]', validator=u'PORTO ACRE')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[12]', validator=u'RIO BRANCO')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[13]', validator=u'SENA MADUREIRA')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[14]', validator=u'SENADOR GUIOMARD')
    client.asserts.assertText(xpath=u'/html/body/form/div/div[1]/div/ul/li[15]', validator=u'XAPURI')