from windmill.authoring import WindmillTestClient

def test_tests_acidentes_rodovias_periodo_windmill():
    client = WindmillTestClient(__name__)

    client.asserts.assertNode(link=u'Consulta')
    client.asserts.assertNode(link=u'Per\xedodo')
    client.click(link=u'Per\xedodo')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertText(xpath=u'/html/body/div[2]/div/div/h4/center', validator=u'Consulta por Per\xedodo')
    client.click(id=u'de')
    client.type(text=u'12345678', id=u'de')
    client.click(id=u'ate')
    client.type(text=u'123456789', id=u'ate')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertText(xpath=u"//div[@id='modalErro']/h2", validator=u'Erro!')
    client.asserts.assertText(xpath=u"//div[@id='modalErro']/p", validator=u'Preencha corretamente o formul\xe1rio!')
    client.click(link=u'\xd7')
    client.click(link=u'Per\xedodo')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(id=u'de')
    client.type(text=u'12/04/2008', id=u'de')
    client.click(id=u'ate')
    client.type(text=u'30/06/2008', id=u'ate')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertNode(link=u'12/04/2008')
    client.asserts.assertNode(link=u'30/06/2008')
    client.asserts.assertNode(xpath=u'/html/body/div[3]/div[1]/div/div/div[1]/h4/span')
    client.asserts.assertText(xpath=u'/html/body/div[3]/div[1]/div/div/div[1]/h4/span', validator=u'364203')
    client.click(link=u'Per\xedodo')
    client.waits.forPageLoad(timeout=u'20000')
    client.click(id=u'de')
    client.type(text=u'17/06/2009', id=u'de')
    client.click(id=u'ate')
    client.type(text=u'30/06/2010', id=u'ate')
    client.click(id=u'btn_submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forPageLoad(timeout=u'20000')
    client.asserts.assertNode(link=u'17/06/2009')
    client.asserts.assertNode(link=u'30/06/2010')
    client.asserts.assertNode(xpath=u'/html/body/div[3]/div[1]/div/div/div[1000]/h4/span')
    client.asserts.assertText(xpath=u'/html/body/div[3]/div[1]/div/div/div[1000]/h4/span', validator=u'543600')